default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dpg-crk7tr1u0jms73fjgtc0-a.frankfurt-postgres.render.com
      port: 5432
      user: admin
      dbname: dev_0hng
      password: "{{ env_var('DBT_ENV_SECRET_PASSWORD') }}"
      schema: dbt
      threads: 4